#!/bin/bash
if [ "$(whoami)" == "root" ] ; then
  echo "You are root user! Now we can continue installation..."
else
  echo "In order to run this script, you need to be root user!"
  exit 0
fi

export dom=$(cat /etc/resolvconf/resolv.conf.d/head | grep search | sed -e 's/\<search\>//g' | sed -e 's/ //g')
export domAdmin=administrator@$dom

apt update && apt purge openresolv -y && apt install resolvconf -y
resolvconf --enable-updates
resolvconf -u

echo "In order to install ADPi, you need a static IP and you need the standard Administrator account enabled on your primary domain controller."
echo "You need to add the following to /etc/resolv.conf.d/resolvconf/head:"
echo "search yourdomain.local"
echo "nameserver 1.2.3.4 [THIS IS THE IP OF YOUR PRIMARY DOMAIN CONTROLLER!!!]"
echo "And you need to add the following to your /etc/hosts"
echo "1.2.3.4 dc01.yourdomain.local dc01"
echo "NOTE: PLEASE REPLACE THE FOLLOWING WITH YOUR OWN DC SPECS ABOVE!!!"
echo "If you've done that, we can continue the installation."

PS3='Did you do that? Do you want to continue? '
options=("Yes" "No")
select ctn in "${options[@]}"
do
	case $ctn in
		"Yes")
			echo "ADPi installing now!"
			echo "During the setup you will be asked for:"
			echo "1. Default Kerberos realm"
			echo "Examples:"
			echo "1. DOMAIN.LOCAL (Case Sensitive)"
			sleep 10
			echo "We will continue installation!"
			sleep 2
			apt install samba smbclient winbind krb5-user krb5-config krb5-locales winbind libpam-winbind libnss-winbind -y
			resolvconf -u
			systemctl stop samba-ad-dc.service smbd.service nmbd.service winbind.service
			systemctl disable samba-ad-dc.service smbd.service nmbd.service winbind.service
			echo "Checking SAMBA config now..."
			smbd -b | grep "CONFIGFILE"
			echo "Setting up the rest of AD..."
			mv /etc/samba/smb.conf /etc/samba/smb.conf.backup
			mv /etc/krb5.conf /etc/krb5.conf.orig
			samba-tool domain join $dom DC -U $domAdmin
			ln -sf /var/lib/samba/private/krb5.conf /etc/krb5.conf
			systemctl unmask samba-ad-dc.service
			systemctl start samba-ad-dc.service
			systemctl enable samba-ad-dc.service
			break 1
		;;
		
		"No")
			break 2
		;;
		*) echo "Invalid option $REPLY";;
	esac
done
echo "Installation done!"
echo "Cheers!"
echo "Please reboot now!"
sleep 2
PS3='Do you want to reboot? '
options=("Yes" "No")
select reb in "${options[@]}"
do
	case $reb in
		"Yes")
			echo "Rebooting now..."
			sleep 2
			reboot
			break 1
		;;
		
		"No")
			echo "Reboot please later!"
			sleep 2
			break 2
		;;
	esac
done
sleep 2
exit 0