#!/bin/bash
if [ "$(whoami)" == "root" ] ; then
  echo "You are root user! Now we can continue installation..."
else
  echo "In order to run this script, you need to be root user!"
  exit 0
fi

apt update && apt purge openresolv -y && apt install resolvconf -y
resolvconf --enable-updates
resolvconf -u

echo "In order to install ADPi, you need a static IP."
echo "You need to add the following to /etc/resolv.conf.d/resolvconf/head:"
echo "search yourdomain.local"

PS3='Did you do that? Do you want to continue? '
options=("Yes" "No")
select ctn in "${options[@]}"
do
	case $ctn in
		"Yes")
			echo "ONE NOTE BEFORE INSTALLING: YOU NEED TO FILL IN DOMAIN.LOCAL IN LOWER CASE WHEN ASKING FOR REALM AFTER KERBEROS ETC."
			echo "ADPi installing now!"
			echo "During the setup you will be asked for:"
			echo "1. Default Kerberos realm"
			echo "2. Kerberos servers"
			echo "3. Administrative server"
			echo "Examples:"
			echo "1. DOMAIN.LOCAL (Case Sensitive)"
			echo "2. domain.local (Lower Case)"
			echo "3. myhostname.domain.local (Lower Case)"
			sleep 10
			echo "We will continue installation!"
			sleep 2
			apt install samba smbclient winbind krb5-user krb5-config krb5-locales winbind libpam-winbind libnss-winbind samba-dsdb-modules -y
			echo "nameserver 8.8.8.8
nameserver 8.8.4.4" >> /etc/resolvconf/resolv.conf.d/head
			resolvconf -u
			systemctl stop samba-ad-dc.service smbd.service nmbd.service winbind.service
			systemctl disable samba-ad-dc.service smbd.service nmbd.service winbind.service
			echo "Checking SAMBA config now..."
			smbd -b | grep "CONFIGFILE"
			echo "Setting up the rest of AD..."
			mv /etc/samba/smb.conf /etc/samba/smb.conf.backup
			mv /etc/krb5.conf /etc/krb5.conf.orig
			samba-tool domain provision --use-rfc2307 --interactive
			ln -sf /var/lib/samba/private/krb5.conf /etc/krb5.conf
			systemctl unmask samba-ad-dc.service
			systemctl start samba-ad-dc.service
			systemctl enable samba-ad-dc.service
			break 1
		;;
		
		"No")
			break 2
		;;
		*) echo "Invalid option $REPLY";;
	esac
done
echo "Installation done!"
echo "Cheers!"
echo "Please reboot now!"
sleep 2
PS3='Do you want to reboot? '
options=("Yes" "No")
select reb in "${options[@]}"
do
	case $reb in
		"Yes")
			echo "Rebooting now..."
			sleep 2
			reboot
			break 1
		;;
		
		"No")
			echo "Reboot please later!"
			sleep 2
			break 2
		;;
	esac
done
sleep 2
exit 0
